User can choose not to delete users
PagerDuty/public-support-scripts pull request #58
Opened 2021-09-14 17:16 UTC by Sesshoumaru404

**Link back to Jira ticket:**

## Description

Allow for script to run without deleting users, helpful if changing a user to a stakeholder

## Implementation

User the `-n` flag to no delete user but remove from teams, schedules and EP

### Steps to test changes
*

## Documentation 
- [x] There is documentation that needs to be updated upon merging these changes

Links to any documentation to be updated:

2021-09-14 17:53 UTC, JosefGoodyear requested changes
I feel like the initial message "{} users to be deleted" will be confusing if they aren't deleting users. Could we add the following line (or something similar) in main:

        if arguments.do_not_delete is True:
            print("{} users to be removed from schedules, teams, and escalation policies. Users will not be deleted."
            .format(len(email_list)))
        else:
            print("{} users to be deleted".format(len(email_list)))

2021-09-14 17:53 UTC, JosefGoodyear commented on user_deprovision/user_deprovision.py
> +        log.info('User %s not removed; "Do not delete user" flag selcted.', user_email)
"selcted" > "selected"  typo

2021-09-14 17:53 UTC, JosefGoodyear commented on user_deprovision/user_deprovision.py
> +        help="Do not delete user but preform all other actions",
"preform" > "perform" typo

2021-09-17 01:56 UTC, ehlerorngard approved these changes
This is great, Paul!  Thanks for doing it.  Works great.  I pushed up Josef's logging edits plus another couple log updates.

2023-09-08 17:20 UTC, ethanmsl commented
Working through very old PR backlog.
I've just merged current master into this branch.
@Sesshoumaru404 -- could you re-rest the script, check that Josef's request is addressed and that you're into Ehler's adds (I assume; just catching us all up on what's happened here) then ping me and I'll review.

If time has worn down memories of this script hit me up and we'll bang through it together.

2023-09-19 14:43 UTC, merged